#!/bin/python3

import sys, db, updown, config

def main():

    if len(sys.argv) != 3:
        print(config.usage)
        return(1)

    command = str(sys.argv[1])
    target = str(sys.argv[2])

    if command == "list" and target == "history":
        db.listDb()
        return(0)

    if command == "list" and target == "keys":
        db.listKeys()
        return(0)

    elif command == "clear" and target == "history":
        db.clearDb()
        return(0)

    elif command == "search":
        db.searchDb(target)
        return(0)

    elif command == "export":
        res = db.exportDb(target)
        if res == 1:
            print("[!] Error exporting history to {}".format(target))
            return(1)
        else:
            print("[+] Successfully exported history to {}".format(target))
            return(0)

    elif command == "save":
        res = db.saveOne(target)
        if res == 1:
            print("[!] Could not find {} in local history".format(target))
            return(1)
        if res == 2:
            print("[!] Error saving {} to local directory".format(target))
            return(1)
        else:
            print("[+] Successfully saved {} to local directory".format(target))
            return(0)

    elif command == "import":
        res = db.importDb(target)
        if res == 1:
            print("[!] Could not read {}".format(target))
            return(1)
        elif res == 2:
            print("[!] Could not import {}".format(target))
            return(1)
        elif res == 3:
            print("[!] No entries in {}".format(target))
            return(1)
        else:
            print("[+] Successfully imported {}".format(target))
            return(0)

    elif command == "delete":
        res = db.deleteItem(target)
        if res == 1:
            print("[!] Could not find {} in history".format(target))
            return(1)
        elif res == 2:
            print("[!] Could not delete {} from history".format(target))
            return(1)
        else:
            print("[+] Successfully deleted {} from history".format(target))
            return(0)

    elif command == "upload":
        res = updown.uploadFile(target)
        if res == 1:
            print("[!] Could not find {}".format(target))
            return(1)
        elif res == 2:
            print("[!] Could not encrypt {}".format(target))
            return(1)
        elif res == 3:
            print("[!] Could not upload {}".format(target))
            return(1)
        elif res == 4:
            print("[!] Could not add an entry for {}".format(target))
            return(1)
        else:
            print("[+] Successfully uploaded {}".format(target))
            return(0)

    elif command == "download":
        res = updown.downloadFile(target)
        if res == 1:
            print("[!] Could not retrieve {} from history".format(target))
            return(1)
        elif res == 2:
            print("[!] Could not download {}".format(target))
            return(1)
        elif res == 3:
            print("[!] Could not decrypt {}".format(target))
            return(1)
        else:
            print("[+] Downloaded {} successfully".format(res))
            return(0)
    else:
        print(config.usage)
        return(1)

if __name__ == "__main__":
    main()