#!/usr/bin/env python3

import os, sys, db, updown, config

def main(command, target):

    if command == "list" and target == "history":
        res = db.listDb()
        if res == 1:
            print("[!] History is empty")

    elif command == "clear" and target == "history":
        db.clearDb()

    elif command == "search":
        res = db.searchDb(target)
        if res == 1:
            print("[!] Could not find any entries for {}".format(target))

    elif command == "add":
        for tar in target.split(','):
            name, hash, key = tar.split(':')
            res = db.addEntry(name, hash, key)
            if res == 1:
                print("[!] Error adding entry to history")
            elif res == 2:
                print("[!] Invalid hash")
            elif res == 3:
                print("[!] Unacceptable key length")
            else:
                print("[+] Successfully added {}".format(name))

    elif command == "export" and target == "history":
        res = db.exportDb(target)
        if res == 1:
            print("[!] Error exporting history")
        else:
            print("[+] Successfully exported history")

    elif command == "save":
        for tar in target.split(','):
            res = db.saveOne(tar)
            if res == 1:
                print("[!] Could not find {} in local history".format(tar))
            elif res == 2:
                print("[!] Error saving {} to local directory".format(tar))
            else:
                print("[+] Successfully saved {} to local directory".format(tar))

    elif command == "import":
        for tar in target.split(','):
            res = db.importDb(tar)
            if res == 1:
                print("[!] Could not read {}".format(tar))
            elif res == 2:
                print("[!] Could not import {}".format(tar))
            elif res == 3:
                print("[!] No entries in {}".format(tar))
            else:
                print("[+] Successfully imported {}".format(tar))

    elif command == "delete":
        for tar in target.split(','):
            res = db.deleteItem(tar)
            if res == 1:
                print("[!] Could not find {} in history".format(tar))
            elif res == 2:
                print("[!] Could not delete {} from history".format(tar))
            else:
                print("[+] Successfully deleted {} from history".format(tar))

    elif command == "upload":
        for tar in target.split(','):
            res = updown.uploadFile(tar)
            if res == 1:
                print("[!] Could not find {}".format(tar))
            elif res == 2:
                print("[!] Could not encrypt {}".format(tar))
            elif res == 3:
                print("[!] Could not upload {}".format(tar))
            elif res == 4:
                print("[!] Could not add an entry for {}".format(tar))
            else:
                print("[+] Successfully uploaded {}".format(tar))

    elif command == "download":
        for tar in target.split(','):
            res = updown.downloadFile(tar)
            if res == 1:
                print("[!] Could not retrieve {} from history".format(tar))
            elif res == 2:
                print("[!] Could not download {}".format(tar))
            elif res == 3:
                print("[!] Could not decrypt {}".format(tar))
            else:
                print("[+] Downloaded {} successfully".format(res))
                
    else:
        print(config.usage)

if __name__ == "__main__":

    if len(sys.argv) != 3:
        print(config.usage)
        exit()

    command = str(sys.argv[1])
    target = str(sys.argv[2])
    
    main(command, target)
